apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
    app: myjavaapp    
spec:
  type: Loadbalancer
  ports:
  - port: 8080
    nodePort: 30005
    protocol: TCP
  selector:
    app: myjavaapp
